[dotfiles."keybindings.json".links]
windows = "~/AppData/Roaming/Code/User/keybindings.json"
mac = "~/Library/Application Support/Code/User/keybindings.json"
linux = "~/.vscode-server/data/Machine/keybindings.json"

[dotfiles."settings.json".links]
windows = "~/AppData/Roaming/Code/User/settings.json"
mac = "~/Library/Application Support/Code/User/settings.json"
linux = "~/.vscode-server/data/User/settings.json"
